Status/urls.py
from django.urls import path

from Status import views

urlpatterns = [
    path('home/', views.BoardListView.as_view(), name='home'),
    path('home/new/',views.new_board,name='new_board'),
    path('home/<pk>/', views.board_topics, name='board_topics'),
    path('home/<pk>/new/', views.new_topic, name='new_topic'),
    path('home/<pk>/topics/<topic_pk>/', views.topic_posts, name='topic_posts'),
    path('boards/<pk>/topics/<topic_pk>/reply/', views.reply_topic, name='reply_topic'),
    path('boards/<pk>/topics/<topic_pk>/posts/<post_pk>/edit/',
        views.PostUpdateView.as_view(), name='edit_post'),

]

helpers/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('Status/',include('Status.urls')),
    path('onetime/',include('onetime.urls'))
]

onetime/urls.py
from django.urls import path
from onetime import views
app_name="onetime"
urlpatterns = [
    path('new/', views.NewView.as_view(), name='new'),
    path('new/create/', views.CreateView.as_view(), name='create'),
    path('new/verify/', views.VerifyView.as_view(), name='verify'),
    path('confirm/', views.ConfirmView.as_view(), name='confirm')
]

onetime/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Phone(models.Model):
	user=models.OneToOneField(User,on_delete=models.PROTECT)
	phone_number=models.CharField(max_length=16)

	def __str__(self):
		return self.phone_number

onetime/views.py
from django.shortcuts import render
from django.views.generic import DetailView,View,TemplateView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout
import nexmo
from onetime .models import Phone
from django.conf import settings

# Create your views here.
class NewView(LoginRequiredMixin,DetailView):
	template_name="onetime/new.html"
	model=Phone

	def get_object(self):
		try:
			return self.request.user.phone
			#if Phone.objects.filter(user=self.request.user).exists():
			#	return self.request.user
		except Phone.DoesNotExist:
			return Phone.objects.create(user=self.request.user)

class CreateView(LoginRequiredMixin,View):
	def post(self,request):
		number=self.find_or_set_number(request)
		response=self.send_verification_request(request,number)
		if (response['status'] == '0'):
			request.session['verification_id'] = response['request_id']
			return HttpResponseRedirect(reverse('onetime:verify')+"?next="+request.POST['next'])
		else:
			logout(request)
			messages.add_message(request, messages.INFO, 'Could not verify your number. Please contact support.')
			return HttpResponseRedirect('/Status/home')

	def find_or_set_number(self, request):
		two_factor = request.user.phone

		if (not two_factor.phone_number):
			two_factor.phone_number = request.POST['number']
			two_factor.save()
 
		return two_factor.phone_number
 
	def send_verification_request(self, request, number):
		client = nexmo.Client(key='26942665',secret='C8SRPIXatgidi3rj')
		return client.start_verification(number=number, brand='helpers')

class VerifyView(LoginRequiredMixin,TemplateView):
	template_name="onetime/verify.html"


class ConfirmView(LoginRequiredMixin, View):
	def post(self, request):
		response = self.check_verification_request(request)

		if (response['status'] == '0'):
			request.session['verified'] = True
			return HttpResponseRedirect('/Status/home')
		else:
			messages.add_message(request, messages.INFO, 'Could not verify code. Please try again.')
			return HttpResponseRedirect(reverse('onetime:verify')+"?next="+request.POST['next'])


	def check_verification_request(self, request):
		return nexmo.Client(key='26942665',secret='C8SRPIXatgidi3rj').check_verification(request.session['verification_id'], code=request.POST['code'])

onetime/templates/onetime/new.html
{% extends 'Status/base.html' %}
 
{% block content %}
 
<form class='form-inline' action="{% url 'onetime:create' %}" method="post">
 
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ request.GET.next }}">
 
  <p>
    To continue we need to verify your phone number.
  </p>
 
  <div class="form-group">
    <input type="text" name="number" value="{{ object.number }}"
           {% if object.number %}disabled{% endif %} class='form-control'>
  </div>
  <div class="form-group">
    <input type="submit" name="name" value="Verify" class='btn btn-primary'>
  </div>
</form>
 
{% endblock %}
 

onetime/templates/onetime/verify.html
{% extends 'Status/base.html' %}
 
{% block content %}
 
<form class='form-inline' action="{% url 'onetime:confirm' %}" method="post">
 
  {% csrf_token %}
  <input type="hidden" name="next" value="{{request.GET.next}}">
 
  <p>
    We have sent a code to your number. Please type it in below.
  </p>
 
  <div class="form-group">
    <input type="text" name="code" class='form-control'>
 
  </div>
  <div class="form-group">
    <input type="submit" name="name" value="Confirm" class='btn btn-primary'>
  </div>
</form>
 
{% endblock %}